### ISSUE TITLE
website is down! 502 bad gateway response

### ISSUE THREAD

**Issue by chandrahas316** [osslab-pku/SILENCE#2]
Hi!

https://licenserec.osslab-pku.org/#/compliance - Your website seems to be down as its returning 502 bad gateway as response. Does anyone else facing this issue??

**Comment by zhcxww** [comment]
It has been fixed！Thank you @chandrahas316 !

**Comment by minghuizhou** [comment]
It's up now.




Minghui







-----原始邮件-----
发件人:"Chandrahas Tummepalli" ***@***.***>
发送时间:2024-10-31 14:24:09 (星期四)
收件人: osslab-pku/SILENCE ***@***.***>
抄送: Subscribed ***@***.***>
主题: [osslab-pku/SILENCE] website is down! 502 bad gateway response (Issue #2)






Hi!

https://licenserec.osslab-pku.org/#/compliance - Your website seems to be down as its returning 502 bad gateway as response. Does anyone else facing this issue??

**Comment by chandrahas316** [comment]
Its still down for me......
![image_2024-10-31_141812466](https://github.com/user-attachments/assets/a7a9987b-4d0a-4449-9308-2ab5f3afb853)

**Comment by zhcxww** [comment]
Sorry! We are troubleshooting the issue and expect to resolve it within a few hours. @chandrahas316

**Comment by zhcxww** [comment]
The service is up again.  If you encounter any issues, please feel free to contact us. @chandrahas316

**Comment by chandrahas316** [comment]
Thank you!!!!!

**Comment by chandrahas316** [comment]
I am sorry to inform but the website again went down, 502 bad gateway error.....
![image_2024-11-01_170003794](https://github.com/user-attachments/assets/22a2b893-d006-4753-b964-919fb46f0acd)

**Comment by zhcxww** [comment]
It is up now.
